# Generated by Django 4.0.1 on 2022-02-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profileimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='1.png', upload_to='users/'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
