# Generated by Django 4.0.1 on 2022-02-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_city_alter_profile_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Here is your bio', null=True),
        ),
    ]
