# Generated by Django 4.0.1 on 2022-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('out-of-stock', 'Hot'), ('new', 'New'), ('price-dec', 'Auction')], max_length=300, null=True),
        ),
    ]
