# Generated by Django 4.0.1 on 2022-02-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('', ''), ('hot', 'Hot'), ('new', 'New'), ('price-dec', 'Auction')], max_length=300, null=True),
        ),
    ]
