# Generated by Django 4.0.1 on 2022-02-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='full_name',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
