# Generated by Django 4.0.1 on 2022-02-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
