# Generated by Django 4.0.1 on 2022-02-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_post_code',
            field=models.CharField(max_length=30, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
