# Generated by Django 4.0.1 on 2022-02-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_billing_address_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_email_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_post_code',
            field=models.EmailField(max_length=30, null=True, verbose_name='Post Code'),
        ),
    ]
